name: Build

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutSource
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: SetUpGo
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: 1.22

    - name: InstallDependencies
      run: |
        go get -u ./cmd/radar/

    - name: Build
      run: go build -v ./cmd/radar/main.go
