name: Build

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutSource
      uses: actions/checkout@v2

    - name: SetUpGo
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      
    - name: UnitTest
      run: go test -v ./test/*
  
  security:
    uses: ./.github/workflows/sonarcloud.yml
    with:
      project-key: ahmetak4n_radar
      organization: ahmetak4n
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
  
      
        
        
        
