name: Build

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutSource
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        fetch-depth: 0

    - name: SetUpGo
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
      with:
        go-version: 1.18

    - name: InstallDependencies
      run: |
        go get -u ./cmd/radar/

    - name: Build
      run: go build -v ./cmd/radar/radar.go

  sonarcloud:
    uses: ahmetak4n/actions/.github/workflows/sonarcloud.yml@main
    permissions:
      contents: read
    needs: build
    with:
      project-key: "ahmetak4n_radar"
      organization: "ahmetak4n"
      sources: "."
      exclusions: "**/*_test.go"
    secrets:
      sonar-cloud-token: ${{ secrets.SONARCLOUD }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  semgrep:
    uses: ahmetak4n/actions/.github/workflows/semgrep.yml@main
    permissions:
      contents: read
      security-events: write
    needs: build
    secrets:
      semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
