name: Build

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutSource
      uses: actions/checkout@v2

    - name: SetUpGo
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      
    - name: UnitTest
      run: go test -v ./test/*
    
    - name: SonarCloud Analyze
      uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
      with:
        args:
          -Dsonar.projectKey=ahmetak4n_radar
          -Dsonar.organization=ahmetak4n
          -Dsonar.sources=${{ github.workspace }}
          -Dsonar.projectBaseDir=${{ github.workspace }}
      
      
        
        
        
