name: Build

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutSource
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SetUpGo
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: InstallDependencies
      run: |
        go get .

    - name: Build
      run: go build -v ./...
      
    - name: UnitTest
      run: go test -v ./test/*
      
      
        
        
        
