name: Build

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutSource
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        fetch-depth: 0

    - name: SetUpGo
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
      with:
        go-version: 1.18

    - name: InstallDependencies
      run: |
        go get .

    - name: Build
      run: go build -v ./...
      
    - name: UnitTest
      run: go test -v ./test/*
  semgrep:
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      discussions: read
      issues: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read
      security-events: write
    uses: ./.github/workflows/semgrep.yml
    needs: build
    secrets:
      semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
  snyk:
    permissions:
      security-events: write
    uses: ./.github/workflows/snyk-security.yml
    needs: build
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
