name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: UnitTest
      run: go test -v ./test/*
      
    - name: SecTest
      uses: securego/gosec@master
      with:
        args: ./..
