name: Semgrep

on:
  workflow_call:
    secrets:
      semgrep-app-token:
        required: true
        
permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          publishToken: ${{ secrets.semgrep-app-token }}
          generateSarif: "1"

      - name: UploadResult
        uses: github/codeql-action/upload-sarif@f3feb00acb00f31a6f60280e6ace9ca31d91c76a
        with:
          sarif_file: semgrep.sarif
        if: always()
