name: Semgrep

on:
  workflow_call:
    secrets:
      semgrep-app-token:
        required: true

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: returntocorp/semgrep-action@master
        with:
          publishToken: ${{ secrets.semgrep-app-token }}
          generateSarif: "1"

      - name: UploadResult
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
