name: SnykSecurity

on:
  workflow_call:
    secrets:
      snyk-token:
        required: true

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutSource
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SetUpGo
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: InstallDependencies
        run: |
          go get .
      
      - name: SetUpSnyk
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          args: --sarif-file-output=snyk.sarif
          command: monitor
      
      - name: UploadResult
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
