name: SonarCloud

on:
  workflow_call:
    secrets:
      sonar-cloud-token:
        required: true
        
permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.sonar-cloud-token }}  
        with:
          args:
            -Dsonar.projectKey=ahmetak4n_radar
            -Dsonar.organization=ahmetak4n
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go
