name: SonarCloud

on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
      organization:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      sonar-token:
        required: true

permissions:
  pull-requests: read

jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Analyze
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.sonar-token }}  
        with:
          args:
            -Dsonar.projectKey=ahmetak4n_radar
            -Dsonar.organization=ahmetak4n
