name: UnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: UnitTest
      run: go test -v ./test/*
